{% set name = "azure-keyvault" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 37a8e5f376eb5a304fcd066d414b5d93b987e68f9212b0c41efa37d429aadd49

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - azure-keyvault-certificates ~=4.2.0
    - azure-keyvault-keys ~=4.2.0
    - azure-keyvault-secrets ~=4.2.0

test:
  imports:
    - azure.keyvault.certificates
    - azure.keyvault.keys
    - azure.keyvault.secrets

about:
  home: https://docs.microsoft.com/en-au/azure/key-vault/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Azure Key Vault client libraries for Python'
  description: |
    This package does not contain any code in itself.
    It installs a set of packages that provide APIs for Key Vault operations.
  doc_url: https://docs.microsoft.com/en-au/azure/key-vault/
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault

extra:
  recipe-maintainers:
    - andreyz4k
    - dhirschfeld
