travis:
  secure:
    BINSTAR_TOKEN: h2gXyJb1j8F0EhvUjR0ZmQLAki1dArrxYnlx+wEYWvwAwsMMzlFmB4ZHpVwLC2zDHojbZxcsGpYm7AtLPNJgWDzkH/mPO15Wv9JnEz/AhJ6cgl4CnQ8xifJRuiEIEKgdOIu3ZFY5xd8gYhy+hCS8SqVoh9t1ZNAAk/XJKKcKlwCTsW2t6JcGGXOh4RZ4Ke5pZodw5nkvcruVj3mp3scFP6taiIAlyj8QynQuOmFzTulzs1kQ7tAGAGGAcwNuzYYCSvsye6GkOTLBBSrOwMaT2Oh18kGGTBzpOonj4M4+tJR037qFJ6ilCGByOgWGAxK90iJIH5y5x2v0VgMI5E8hK8uzk6cxD4PH2yK7bg9nJYuKUE6JX/nkmTHv4gyZNovk5nqdJGc368IE4FhMfWD7IJdT7Fk5/aHWndtlH9yeEzsNW8TsjlcvtFfFtrTGvIALgVdSy2o6RsoyVCFHEscn5zDPiiiEok6ow/Q4xtncYlPYk5x24rsVh0gMMZpKea5s4166JDuDOYIy/ea8IpMV37ogyVaJOY9DyjEgDl4KB8Rz1v9g29B0vpfeioJcedOBNJ2pfACVzW4TXNaaQiRh4IjlXG26dFvV68xhxwXL/6x2uIdKqj7ysHtZd7tv+49LPhk+kSnN8hbgKLsAtvKOQYSQ50igITcHoc3z31kDu6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
