travis:
  secure:
    BINSTAR_TOKEN: NufgNkmiEnLOhheWj5TnI5UtgTjKxXc6vWt4WRuYe3s01I7Zq37QReyn+ec8IwBPOsA7KKZKNy3vV/EA10Xyn6LVx/ZFNwrqw7CVDAsrWlRuLIoqm9TWe2w0ZHvty9hNjwYNfFrJ+r5WNArjftLtFeC5yBkEJZvZuHGnLxkXqx5siyhC9OwG5PnB5FBj9VQpYczbebpe4VNsaJtCctvXmEmewer4OcYW3i5b9SjRLZm7fT5FsGBb/W6KDEj+tNcoSOSqU9Qyy8kdJQwYgFu83CkSjTBtq3AFf4lx4OwkF9zg1Ppst35fJDgPqTz0MEcugbN3T1wBuHpyGfqxWANT0r9R9938tifXaXh3PwQk7B+qmDPRTcQo5YuaEUtgavY3nBqAbs+0hj6/A52pCDyCNh5wdHt6MfNuUdBu0P+H4SXZf7c0UaqYuVyQg/z0vqh/BHZhNwFUjex2le5+PdskS30VlZQf4i46Wu7EdTVl5L3IBfq+sDgwzCbWgLe0Ifk9BdeDLXlWk9aJZg6cZRph4N8GzuHCPfMelu4l/72WMQPv+8CrLCS+xY9KlQ7l8UDpHFLUKHic84xhevKsnaNv8cAEvtFQ/B3GHQAxO9slRYwcoq6C5C929dfHZ6hjhnhB/kQk8jQkH7uaT/b5LHR0vgdPWwVWtmiE1yc5R0QZZ4s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
